### ISSUE TITLE
Support for Laravel 5.8.X

### ISSUE THREAD

**Issue by Tillix95** [techsemicolon/laravel-php-latex#2]
Please add support for Laravel / Illuminate 5.8.X

**Comment by techsemicolon** [comment]
I am testing the same currently, I do not think there is anything which will break in 5.8. I will keep you posted with final results and if any updates. 👍 Thanks for following up

**Comment by akmet** [comment]
I'm also very interested in using this in Laravel 5.8 and noticed that you need to update the `Event::fire` to `Event::dispatch`. This comes in [5.4](https://laravel.com/docs/5.4/upgrade).

Also I had problems with the binary. It tried to run `./pdflatex`, since I didn't used this before I cannot say if it is caused by 5.8 or regarding to my homestead setup. Using `->binPath('/usr/bin/pdflatex')` solved this problem.

When you need any help with testing, please feel free to ask! :-)

**Comment by techsemicolon** [comment]
Thanks @akmet I am pushing a new version for laravel 5.8 this week. Thanks for your interest in this, will definitely ask for help when needed :)

**Comment by necrogami** [comment]
Any update on this? Laravel 6.0 is only a few days away(Sept 3rd release date). I've got a project i'm starting soon and would love to use this.

**Comment by carpad88** [comment]
Well, Laravel 6 was already release, Are there some news about making it compatible with this new version? I'm working in a project and this package would be very helpful
